# This file defines how things are displayed in HA, options that show, etc.
name: Traefik
version: 3.7.5.b
slug: traefik
description: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
arch:
  - aarch64
  - amd64
startup: system
init: false
stage: stable
boot: auto
url: https://github.com/boomam/home-assistant-addons/tree/master/traefik
ports:
  80/tcp: 80
  443/tcp: 443
  9901/tcp: null
  9991/tcp: null
  9992/tcp: null
  9993/tcp: null
  9994/tcp: null
  9995/tcp: null
  9996/tcp: null
  9997/tcp: null
  9998/tcp: null
  9999/tcp: null
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
  9991/tcp: "Extra entrypoint websecure9991 (optional)"
  9992/tcp: "Extra entrypoint websecure9992 (optional)"
  9993/tcp: "Extra entrypoint websecure9993 (optional)"
  9994/tcp: "Extra entrypoint websecure9994 (optional)"
  9995/tcp: "Extra entrypoint websecure9995 (optional)"
  9996/tcp: "Extra entrypoint websecure9996 (optional)"
  9997/tcp: "Extra entrypoint websecure9997 (optional)"
  9998/tcp: "Extra entrypoint websecure9998 (optional)"
  9999/tcp: "Extra entrypoint websecure9999 (optional)"
ingress: true
ingress_entry: dashboard/
hassio_role: default
hassio_api: true
panel_icon: mdi:earth-arrow-right
map:
  - config
  - share
  - ssl:rw
options:
  log_level: error
  access_logs: false
  forwarded_headers_insecure: false
  insecure_skip_verify: false
  dynamic_configuration_path: "/config/traefik/"
  letsencrypt:
    enabled: false
    resolvers:
      - 1.1.1.1:53
    email: youremail@domain.com
    challenge_type: dnsChallenge
    provider: cloudflare
    delayBeforeCheck: 10
  extra_entrypoint_9991: false
  extra_entrypoint_9992: false
  extra_entrypoint_9993: false
  extra_entrypoint_9994: false
  extra_entrypoint_9995: false
  extra_entrypoint_9996: false
  extra_entrypoint_9997: false
  extra_entrypoint_9998: false
  extra_entrypoint_9999: false
  env_vars: []
schema:
  log_level: list(trace|debug|info|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  insecure_skip_verify: bool
  proxy_protocol_trusted_ips:
    - str?
  dynamic_configuration_path: str
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  extra_entrypoint_9991: bool
  extra_entrypoint_9992: bool
  extra_entrypoint_9993: bool
  extra_entrypoint_9994: bool
  extra_entrypoint_9995: bool
  extra_entrypoint_9996: bool
  extra_entrypoint_9997: bool
  extra_entrypoint_9998: bool
  extra_entrypoint_9999: bool
  env_vars:
    - str
