ARG BUILD_FROM=ghcr.io/hassio-addons/base:20.1.0
FROM $BUILD_FROM

ARG BUILD_ARCH
ARG TRAEFIK_VERSION=3.7.5

RUN if [ "${BUILD_ARCH}" = "aarch64" ]; then BUILD_ARCH=arm64; fi && \
    apk add --no-cache nginx gomplate && \
    TRAEFIK_ARTIFACT="traefik_v${TRAEFIK_VERSION}_linux_${BUILD_ARCH}.tar.gz" && \
    TRAEFIK_RELEASE_URL="https://github.com/traefik/traefik/releases/download/v${TRAEFIK_VERSION}" && \
    cd /tmp && \
    wget --quiet -O "${TRAEFIK_ARTIFACT}" "${TRAEFIK_RELEASE_URL}/${TRAEFIK_ARTIFACT}" && \
    wget --quiet -O traefik_checksums.txt "${TRAEFIK_RELEASE_URL}/traefik_v${TRAEFIK_VERSION}_checksums.txt" && \
    grep "  ${TRAEFIK_ARTIFACT}\$" traefik_checksums.txt | sha256sum -c - && \
    tar xzvf "${TRAEFIK_ARTIFACT}" -C /usr/local/bin traefik && \
    chmod +x /usr/local/bin/traefik && \
    rm -f /tmp/*

COPY rootfs /

LABEL \
    io.hass.name="Treafik for ${BUILD_ARCH}" \
    io.hass.description="Home Assistant Unofficial Add-on: ${BUILD_ARCH} Traefik image" \
    maintainer="BoomAM" \
    org.opencontainers.image.title="Traefik for ${BUILD_ARCH}" \
    org.opencontainers.image.description="Home Assistant Unofficial Add-on: ${BUILD_ARCH} Traefik image" \
    org.opencontainers.image.vendor="BoomAM" \
    org.opencontainers.image.authors="BoomAM" \
    org.opencontainers.image.url="https://github.com/boomam/home-assistant-addons" \
    org.opencontainers.image.source="https://github.com/boomam/home-assistant-addons" \
    org.opencontainers.image.documentation="https://github.com/boomam/home-assistant-addons/blob/master/traefik/README.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.revision=${BUILD_REF} \
    org.opencontainers.image.version=${BUILD_VERSION}
