name: "ATT RG JSON API"
description: "Exposes AT&T DSL/Fiber Stats as a JSON API for easy Home Assistant consumption."
image: johhenkens/att_rg_to_json
environment:
  USE_HOSTNAME: "true"
panel_icon: mdi:web
version: "1.2.1"
slug: "attrg2json"
init: false
startup: application
ingress: true
ingress_port: 8080
ingress_entry: /template
watchdog: http://[HOST]:[PORT:8080]/healthcheck
ports:
  8080/tcp:
arch:
  - aarch64
  - amd64
